parameters:
#    walkthrough.example.class: ParkThroughBundle\Example

services:
#   walkthrough.example:
#        class: %ParkThrough.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
