<?php

namespace Park\CrudBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Akb48Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Akb48Repository extends EntityRepository
{
}
