<?php

namespace Park\CrudBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonsRepository extends EntityRepository
{
	public function findAllOrderedByName()
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT p FROM ParkCrudBundle:Persons p ORDER BY p.name ASC'
		)
		->getResult();
	}
}
