SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `gaia`.`GAIA_USER_ACCOUNT` 
CHANGE COLUMN `created_time` `created_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' AFTER `take_over_id_crc32`;

ALTER TABLE `gaia`.`GAIA_MST_GACHA` 
CHANGE COLUMN `gacha_type_id` `gacha_type_id` INT(11) NOT NULL COMMENT 'ガチャタイプID' ,
CHANGE COLUMN `effective_from` `effective_from` DATETIME NOT NULL COMMENT '利用可能期間 from' ,
CHANGE COLUMN `effective_to` `effective_to` DATETIME NOT NULL COMMENT '利用可能期間 to' ;

ALTER TABLE `gaia`.`GAIA_MST_GACHA_CARD` 
CHANGE COLUMN `asset_type_id` `asset_type_id` INT(11) NOT NULL COMMENT 'アセットタイプID（通常はカード関連になるはず）' ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
